-- Archive then remove all Amazon-grading-program (`amzn.gr.*`) ghost SKU rows
-- from fnsku_map. These are auto-generated by Amazon for returned/relisted units
-- and routinely deleted by sellers in Seller Central. The get-fnsku function will
-- re-seed any that live FBA Summaries currently confirm as active.

INSERT INTO public.ghost_sku_quarantine (
  user_id, asin, seller_sku, fnsku, reason, source_function, raw
)
SELECT
  sa.user_id,
  fm.asin,
  fm.seller_sku,
  fm.fnsku,
  'AMZN_GR_GHOST_SKU_PURGE',
  'manual_amzn_gr_purge',
  jsonb_build_object(
    'condition', fm.condition,
    'seller_id', fm.seller_id,
    'marketplace_id', fm.marketplace_id
  )
FROM public.fnsku_map fm
LEFT JOIN public.seller_authorizations sa
  ON sa.seller_id = fm.seller_id AND sa.marketplace_id = fm.marketplace_id
WHERE fm.seller_sku ILIKE 'amzn.gr.%'
  AND sa.user_id IS NOT NULL
ON CONFLICT (user_id, asin, seller_sku, source_function) DO NOTHING;

DELETE FROM public.fnsku_map
WHERE seller_sku ILIKE 'amzn.gr.%';

-- Bust eligibility cache for affected ASINs so banners/results recompute.
DELETE FROM public.fba_eligibility_cache
WHERE asin IN (
  SELECT DISTINCT asin FROM public.ghost_sku_quarantine
  WHERE source_function = 'manual_amzn_gr_purge'
);
